"""FastAPI application entry point and REST API orchestrator for DocuMind AI.

This module provides the API endpoints for health status, document ingestion & vector indexing,
RAG conversational Q&A, structured entity extraction, multi-document comparison, and autonomous
agent analysis.
"""

from functools import lru_cache
from pathlib import Path
import uuid
from typing import TYPE_CHECKING

from fastapi import (
    FastAPI,
    File,
    Form,
    HTTPException,
    UploadFile,
    status,
)
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from app.agents.document_agent import DocumentAgent
from app.core.config import settings
from app.core.logger import get_logger
from app.document.loader import SUPPORTED_EXTENSIONS, DocumentLoader
from app.document.ocr import OCRProcessor
from app.document.preprocessing import TextPreprocessor
from app.models.schemas import (
    ChatRequest,
    ChatResponse,
    ComparisonResult,
    ProcessedDocument,
)
from app.rag.chunker import DocumentChunker
from app.rag.pipeline import RAGPipeline
from app.rag.vector_store import VectorStoreService
from app.services.comparison_service import ComparisonService
from app.services.extraction_service import (
    ExtractionService,
    StructuredExtractionResult,
)

logger = get_logger(__name__)

# =====================================================================
# Application Lifecycle & FastAPI Setup
# =====================================================================

app = FastAPI(
    title=settings.PROJECT_NAME,
    description=settings.PROJECT_DESCRIPTION,
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# Development CORS Middleware (configured for local development and Streamlit frontend)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:8501",
        "http://127.0.0.1:8501",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =====================================================================
# API Request & Response Schemas
# =====================================================================

class HealthResponse(BaseModel):
    """Health check status response payload."""

    status: str = Field(default="healthy", description="Operational status of the API")
    service: str = Field(default="documind-ai", description="Service identifier")


class DocumentUploadResponse(BaseModel):
    """Response returned upon successful document upload, processing, and indexing."""

    message: str = Field(..., description="Status summary message")
    document_id: str = Field(..., description="Unique identifier generated for the document")
    filename: str = Field(..., description="Original name of the uploaded document")
    document_type: str = Field(..., description="Extension or format type of the document")
    total_pages: int = Field(..., description="Total pages parsed in the document")
    chunks_indexed: int = Field(..., description="Number of text chunks embedded and stored in FAISS")


class AgentQueryRequest(BaseModel):
    """Payload for autonomous document analysis agent queries."""

    question: str = Field(..., min_length=1, description="Question or task instruction for the agent")
    document_ids: list[str] | None = Field(
        default=None,
        description="Optional list of document IDs to scope retrieval",
    )
    document_text: str | None = Field(
        default=None,
        description="Optional full document text (required when requesting structured extraction)",
    )
    document_id: str | None = Field(
        default=None,
        description="Optional primary document ID",
    )
    filename: str | None = Field(
        default=None,
        description="Optional primary document filename",
    )
    document_type: str | None = Field(
        default=None,
        description="Optional document category or classification hint",
    )


class AgentQueryResponse(BaseModel):
    """Response returned by the autonomous document analysis agent."""

    answer: str = Field(..., description="Grounded answer or extraction result generated by the agent")


# =====================================================================
# Service Factories / Singletons
# =====================================================================

@lru_cache
def get_document_loader() -> DocumentLoader:
    """Return a cached DocumentLoader instance."""
    return DocumentLoader()


@lru_cache
def get_ocr_processor() -> OCRProcessor:
    """Return a cached OCRProcessor instance."""
    return OCRProcessor()


@lru_cache
def get_text_preprocessor() -> TextPreprocessor:
    """Return a cached TextPreprocessor instance."""
    return TextPreprocessor()


@lru_cache
def get_document_chunker() -> DocumentChunker:
    """Return a cached DocumentChunker instance."""
    return DocumentChunker()


@lru_cache
def get_vector_store_service() -> VectorStoreService:
    """Return a cached VectorStoreService instance."""
    return VectorStoreService()


@lru_cache
def get_rag_pipeline() -> RAGPipeline:
    """Return a cached RAGPipeline instance."""
    return RAGPipeline()


@lru_cache
def get_extraction_service() -> ExtractionService:
    """Return a cached ExtractionService instance."""
    return ExtractionService()


@lru_cache
def get_comparison_service() -> ComparisonService:
    """Return a cached ComparisonService instance."""
    return ComparisonService()


@lru_cache
def get_document_agent() -> "DocumentAgent":
    """Return a cached DocumentAgent instance."""
    from app.agents.document_agent import DocumentAgent

    return DocumentAgent()


# =====================================================================
# Helper Utilities
# =====================================================================

def _ensure_upload_directory() -> Path:
    """Ensure the upload directory exists and return its resolved path."""
    upload_dir = settings.RAW_DATA_DIR / "uploads"
    upload_dir.mkdir(parents=True, exist_ok=True)
    return upload_dir


def _save_upload_file(file: UploadFile) -> Path:
    """Safely validate, sanitize, and persist an uploaded file to disk.

    Args:
        file: Uploaded file from the HTTP request.

    Returns:
        Path: Path to the saved file on disk.

    Raises:
        HTTPException: If file is missing, empty, or has an unsupported extension.
    """
    if not file.filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Uploaded file must have a valid filename.",
        )

    # Sanitize filename (strip directory traversal characters)
    original_name = Path(file.filename).name
    ext = Path(original_name).suffix.lower()

    if ext not in SUPPORTED_EXTENSIONS:
        formatted_supported = ", ".join(sorted(SUPPORTED_EXTENSIONS))
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unsupported file format '{ext}'. Supported formats: {formatted_supported}",
        )

    try:
        contents = file.file.read()
    except Exception as exc:
        logger.error("Failed to read uploaded file '%s': %s", original_name, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to read uploaded file.",
        ) from exc
    finally:
        file.file.close()

    # Verify that file is not empty
    if not contents or len(contents) == 0:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The uploaded file is empty.",
        )

    upload_dir = _ensure_upload_directory()
    unique_filename = f"{uuid.uuid4().hex}_{original_name}"
    target_path = upload_dir / unique_filename

    try:
        target_path.write_bytes(contents)
    except Exception as exc:
        logger.error("Failed to save uploaded file '%s': %s", original_name, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to store uploaded file on the server.",
        ) from exc

    return target_path


def _load_and_preprocess_document(file_path: Path) -> ProcessedDocument:
    """Run the standard ingestion pipeline: load, OCR (if image), and preprocess.

    Args:
        file_path: Path to the saved document.

    Returns:
        ProcessedDocument: Cleaned and structured document.

    Raises:
        HTTPException: If any step of document extraction fails.
    """
    loader = get_document_loader()
    ocr = get_ocr_processor()
    preprocessor = get_text_preprocessor()

    try:
        raw_doc = loader.load(file_path)
        ocr_doc = ocr.process(raw_doc)
        processed_doc = preprocessor.process(ocr_doc)
        return processed_doc
    except (FileNotFoundError, ValueError) as exc:
        logger.warning("Document processing error for '%s': %s", file_path.name, exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.error("Unexpected error loading document '%s': %s", file_path.name, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to process document content.",
        ) from exc


# =====================================================================
# Endpoints
# =====================================================================

@app.get(
    "/",
    summary="Root Endpoint",
    tags=["System"],
)
async def root() -> dict[str, str]:
    """Root endpoint welcoming users and directing them to API documentation."""
    return {
        "message": "Welcome to DocuMind AI API",
        "docs": "/docs",
        "redoc": "/redoc",
        "health": "/health",
    }


@app.get(
    "/health",
    response_model=HealthResponse,
    summary="Health Check",
    tags=["System"],
)
async def health_check() -> HealthResponse:
    """Check the health status of the DocuMind AI API service."""
    return HealthResponse(status="healthy", service="documind-ai")


@app.post(
    "/documents/upload",
    response_model=DocumentUploadResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Upload and Index Document",
    tags=["Documents"],
)
async def upload_document(
    file: UploadFile = File(description="Document file to upload (PDF, PNG, JPG, JPEG)"),
) -> DocumentUploadResponse:
    """Upload a document, perform OCR/normalization, split into chunks, and index in FAISS."""
    original_filename = Path(file.filename or "unknown").name
    logger.info("Received document upload request for '%s'", original_filename)

    saved_path = _save_upload_file(file)
    processed_doc = _load_and_preprocess_document(saved_path)

    chunker = get_document_chunker()
    vector_store_service = get_vector_store_service()

    try:
        chunks = chunker.chunk(processed_doc)
        if not chunks:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="No readable text could be extracted or chunked from the uploaded document.",
            )

        if vector_store_service.exists():
            vector_store_service.add_documents(chunks)
        else:
            vector_store_service.create(chunks)

        logger.info(
            "Document '%s' successfully indexed (doc_id=%s, chunks=%d)",
            processed_doc.metadata.filename,
            processed_doc.metadata.document_id,
            len(chunks),
        )

        return DocumentUploadResponse(
            message="Document processed successfully",
            document_id=processed_doc.metadata.document_id,
            filename=processed_doc.metadata.filename,
            document_type=processed_doc.metadata.file_type,
            total_pages=processed_doc.metadata.total_pages,
            chunks_indexed=len(chunks),
        )

    except HTTPException:
        raise
    except ValueError as exc:
        logger.warning("Indexing validation error for '%s': %s", original_filename, exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.error("Failed to index document '%s': %s", original_filename, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate embeddings and index document in vector store.",
        ) from exc


@app.post(
    "/chat",
    response_model=ChatResponse,
    summary="RAG Conversational Q&A",
    tags=["RAG"],
)
async def chat_with_documents(request: ChatRequest) -> ChatResponse:
    """Answer factual user questions grounded in indexed documents with page-level citations."""
    logger.info("Received RAG chat query: '%s'", request.question[:80])

    rag_pipeline = get_rag_pipeline()

    try:
        response = rag_pipeline.answer(
            question=request.question,
            top_k=request.top_k,
            document_ids=request.document_ids or None,
        )
        return response
    except FileNotFoundError as exc:
        logger.warning("Vector store not found during chat query: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Vector store index not found. Please upload and index documents first.",
        ) from exc
    except ValueError as exc:
        logger.warning("Invalid chat request parameters: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.error("RAG pipeline execution failure: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to generate answer from document collection.",
        ) from exc


@app.post(
    "/documents/extract",
    response_model=StructuredExtractionResult,
    summary="Structured Document Extraction",
    tags=["Extraction"],
)
async def extract_document_structure(
    file: UploadFile = File(description="Document file to extract structured fields from"),
    document_type: str | None = Form(default=None, description="Optional document category hint"),
) -> StructuredExtractionResult:
    """Extract structured key-value entities, classifications, and summaries from a document."""
    original_filename = Path(file.filename or "unknown").name
    logger.info("Received structured extraction request for '%s'", original_filename)

    saved_path = _save_upload_file(file)
    processed_doc = _load_and_preprocess_document(saved_path)

    extraction_service = get_extraction_service()

    try:
        result = extraction_service.extract_from_document(
            document=processed_doc,
            document_type=document_type,
        )
        return result
    except ValueError as exc:
        logger.warning("Structured extraction validation error for '%s': %s", original_filename, exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.error("Structured extraction failed for '%s': %s", original_filename, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to extract structured entities from document.",
        ) from exc


@app.post(
    "/documents/compare",
    response_model=ComparisonResult,
    summary="Compare Two Documents",
    tags=["Comparison"],
)
async def compare_documents(
    file1: UploadFile = File(description="First document to compare (Document A)"),
    file2: UploadFile = File(description="Second document to compare (Document B)"),
) -> ComparisonResult:
    """Compare two documents field-by-field and detect discrepancies."""
    fn1 = Path(file1.filename or "file1").name
    fn2 = Path(file2.filename or "file2").name
    logger.info("Received document comparison request for '%s' and '%s'", fn1, fn2)

    saved_path1 = _save_upload_file(file1)
    saved_path2 = _save_upload_file(file2)

    doc1 = _load_and_preprocess_document(saved_path1)
    doc2 = _load_and_preprocess_document(saved_path2)

    comparison_service = get_comparison_service()

    try:
        result = comparison_service.compare_documents(
            document_a_text=doc1.full_text,
            document_b_text=doc2.full_text,
            document_a_id=doc1.metadata.document_id,
            document_b_id=doc2.metadata.document_id,
            document_a_filename=doc1.metadata.filename,
            document_b_filename=doc2.metadata.filename
        )
        return result
    except ValueError as exc:
        logger.warning("Document comparison validation error: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.error("Document comparison failed between '%s' and '%s': %s", fn1, fn2, exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to compare documents.",
        ) from exc


@app.post(
    "/agent/query",
    response_model=AgentQueryResponse,
    summary="Agent Document Analysis",
    tags=["Agent"],
)
async def query_document_agent(request: AgentQueryRequest) -> AgentQueryResponse:
    """Run autonomous multi-step document analysis using the tool-calling DocumentAgent."""
    logger.info("Received agent query: '%s'", request.question[:80])

    agent = get_document_agent()

    try:
        answer = agent.run(
            question=request.question,
            document_ids=request.document_ids,
            document_text=request.document_text,
            document_id=request.document_id,
            filename=request.filename,
            document_type=request.document_type,
        )
        return AgentQueryResponse(answer=answer)
    except ValueError as exc:
        logger.warning("Agent query validation error: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.error("Agent execution failure: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to process agent query.",
        ) from exc


# =====================================================================
# Development Entry Point
# =====================================================================

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app.api.main:app",
        host=settings.API_HOST,
        port=settings.API_PORT,
        reload=True,
    )
